### ISSUE TITLE
必须每个.vue文件都Import i18n吗？

### ISSUE THREAD

**Issue by KimChan2013** [intlify/vite-vue-i18n-starter#3]
怎么样可以全局使用，不用每个文件都import一遍呢？

**Comment by kazupon** [comment]
Thank you for your feedback.
Sorry, I could not speak Chinese.
If you could speak English, please open with using it.

Thanks.

**Comment by KimChan2013** [comment]
Hello Kazupon,

Sorry I didn't notice that.. since I was checking some other repos in Chinese, I typed in Chinese here.
I want to ask that if it is necessary that the 'import i18n' is needed in every .vue file?
In main.ts the app use it 'app.use', why we still need to import again in each file.

Br,
Kim

**Comment by kazupon** [comment]
why do `app.use` an i18n instance created with `createI18n`, you need to make Vue recognize vue i18n as a plugin. Without `app.use`, i18n will not work in Vue applications. If you don't do `app.use`, i18n won't work in your Vue application, and you also won't be able to use debugging such as vue devtools.

Please read the documentation.
https://vue-i18n.intlify.dev

Thanks!

**Comment by KimChan2013** [comment]
Yes, I can understand to call app.use and actually I called.
![image](https://user-images.githubusercontent.com/9462240/107349744-8aa3da00-6b03-11eb-9289-c08d9752a79c.png)
Referring to this document, it shall be able to use this.$i18n everywhere which is not in my case.
![image](https://user-images.githubusercontent.com/9462240/107349990-d8b8dd80-6b03-11eb-899f-cab74251e411.png)
![image](https://user-images.githubusercontent.com/9462240/107350016-e1111880-6b03-11eb-85f3-3eeb584c5fd1.png)

Thanks!

**Comment by kazupon** [comment]
Hmm, 🤔 
I seem that you use `Legacy API` mode.
`vite-vue-i18n-starter` is setup with `Composition API` mode.

If you can try to use `Legacy API`, you need to set `vite.config.ts`.
About details, see the `vite-plugin-vue-i18n` docs
https://github.com/intlify/vite-plugin-vue-i18n

About that thing, we had not written in `README.md`
Sorry, poor documentation.

If you vue-i18n learn the first time, we recommend that you follow the guide to learn.

**Comment by KimChan2013** [comment]
Ah!!! This is good for me: https://vue-i18n-next.intlify.dev/guide/advanced/composition.html#global-scope-2
Now I am still trying to check how to also make 't' function global instead of 
`  setup: () => {
    const count = ref(0);
    const { t } = useI18n();
    return { count, t };
},`
each component file.
